[project]
name = "etan-ims"
version = "0.0.1"
description = "Inventory Management System"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.1",
    "pillow>=12.1.0",
    "python-dotenv>=1.2.1",
]
